repos:
  # --- General File Hygiene ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict

  # --- Terraform (one source for all Terraform checks) ---
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.101.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      # Optional: generates module docs; comment out if you don't want auto-edits
      - id: terraform_docs
        args: ["--args=--sort-by required"]

  # --- Python (Formatting & Linting) ---
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings
        args: ["--max-line-length=100", "--ignore=E203,W503"]

  # --- YAML & JSON Formatting ---
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: ["-d", "{extends: default, rules: {line-length: disable}}"]

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.34.0
    hooks:
      - id: check-jsonschema
        files: \.json$
